services:

  db_auth_service:
    image: mysql:9.3
    container_name: db_auth_service
    restart: unless-stopped
    volumes:
      - dbfile:/var/lib/mysql
    env_file:
      - auth_service/.env_db
    networks:
      - app

  auth_service:
    container_name: auth_service
    build:
      context: auth_service/
      dockerfile: ./Dockerfile
    depends_on:
      - db_auth_service
      - redis
    env_file:
      - auth_service/.env
    networks:
      - app

    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://auth_service:8228/users/health_check" ]
      interval: 5s
      retries: 20


  kraken_d:
    container_name: kraken_d
    build:
      context: ./kraken_d
      dockerfile: ./Dockerfile

    depends_on:
      auth_service:
        condition: service_healthy

    ports:
      - "8080:8080"
    networks:
      - app

  redis:
    image: redis:8.0.2
    container_name: redis
    restart: always
    networks:
      - app


networks:
  app:
    driver: bridge

volumes:
  dbfile:
    driver: local